CONFIG_SPI=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_MOUSE=y

# SENSITIVITY FIX
# Lowering this to 600 makes the ball less "twitchy"
CONFIG_PMW3610_CPI=600
CONFIG_PMW3610_CPI_DIVIDOR=4

# ACCELERATION FIX
# Turning this OFF (n) makes the movement linear and predictable
CONFIG_PMW3610_SMART_ALGORITHM=n

# Smooth polling
CONFIG_ZMK_MOUSE_TICK_DURATION=8
CONFIG_ZMK_TRACKBALL_POLL_DURATION=10
