CONFIG_SPI=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_MOUSE=y

# SENSITIVITY FIX: This version actually worked.
CONFIG_PMW3610_CPI=600
CONFIG_PMW3610_CPI_DIVIDOR=4

# ACCELERATION FIX: Linear movement.
CONFIG_PMW3610_SMART_ALGORITHM=n

# Polling rates that the sensor accepted.
CONFIG_ZMK_MOUSE_TICK_DURATION=8
CONFIG_PMW3610_ORIENTATION_90=y
CONFIG_PMW3610_INVERT_X=y

# Power Management
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=100
CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=200
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=300
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=500
